Bad Request: /api/v1/papers/generate/ai/
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 4645
"GET /static/drf_spectacular_sidecar/swagger-ui-dist/swagger-ui.css HTTP/1.1" 200 155212
"GET /static/drf_spectacular_sidecar/swagger-ui-dist/swagger-ui-standalone-preset.js HTTP/1.1" 200 229223
"GET /static/drf_spectacular_sidecar/swagger-ui-dist/swagger-ui-standalone-preset.js HTTP/1.1" 200 229223
"GET /static/drf_spectacular_sidecar/swagger-ui-dist/swagger-ui-bundle.js HTTP/1.1" 200 1485855
"GET /api/schema/ HTTP/1.1" 200 211105
"GET /static/drf_spectacular_sidecar/swagger-ui-dist/favicon-32x32.png HTTP/1.1" 200 628
"GET /static/drf_spectacular_sidecar/swagger-ui-dist/swagger-ui-bundle.js HTTP/1.1" 200 1485855
Unauthorized: /api/v1/papers/generate/ai/
"POST /api/v1/papers/generate/ai/ HTTP/1.1" 401 75
"GET / HTTP/1.1" 200 4645
"GET /static/drf_spectacular_sidecar/swagger-ui-dist/swagger-ui-bundle.js HTTP/1.1" 304 0
"GET /static/drf_spectacular_sidecar/swagger-ui-dist/swagger-ui.css HTTP/1.1" 304 0
"GET /static/drf_spectacular_sidecar/swagger-ui-dist/swagger-ui-standalone-preset.js HTTP/1.1" 304 0
"GET /static/drf_spectacular_sidecar/swagger-ui-dist/swagger-ui-standalone-preset.js HTTP/1.1" 304 0
"GET /static/drf_spectacular_sidecar/swagger-ui-dist/swagger-ui-bundle.js HTTP/1.1" 304 0
"GET /api/schema/ HTTP/1.1" 200 211105
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4302
"GET /static/admin/css/base.css HTTP/1.1" 200 22120
"GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2808
"GET /static/admin/css/login.css HTTP/1.1" 200 951
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
"GET /static/admin/css/responsive.css HTTP/1.1" 200 16565
"GET /static/admin/js/theme.js HTTP/1.1" 200 1653
"GET /static/admin/js/theme.js HTTP/1.1" 200 1653
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 4065
"POST /admin/login/?next=/admin/ HTTP/1.1" 200 4468
"POST /admin/login/?next=/admin/ HTTP/1.1" 200 4484
"POST /admin/login/?next=/admin/ HTTP/1.1" 200 4484
"POST /admin/login/?next=/admin/ HTTP/1.1" 200 4482
Watching for file changes with StatReloader
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4302
"GET /static/admin/css/base.css HTTP/1.1" 304 0
"GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
"GET /static/admin/css/login.css HTTP/1.1" 304 0
"GET /static/admin/css/responsive.css HTTP/1.1" 304 0
"GET /static/admin/js/theme.js HTTP/1.1" 304 0
"GET /static/admin/js/theme.js HTTP/1.1" 304 0
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
"POST /admin/login/?next=/admin/ HTTP/1.1" 200 4482
"POST /admin/login/?next=/admin/ HTTP/1.1" 200 4482
"POST /admin/login/?next=/admin/ HTTP/1.1" 200 4482
"POST /admin/login/?next=/admin/ HTTP/1.1" 200 4482
"POST /admin/login/?next=/admin/ HTTP/1.1" 200 4477
Watching for file changes with StatReloader
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4302
"GET /static/admin/css/base.css HTTP/1.1" 304 0
"GET /static/admin/js/theme.js HTTP/1.1" 304 0
"GET /static/admin/css/responsive.css HTTP/1.1" 304 0
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
"GET /static/admin/css/login.css HTTP/1.1" 304 0
"GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
"GET /static/admin/js/theme.js HTTP/1.1" 304 0
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
"POST /admin/login/?next=/admin/ HTTP/1.1" 200 4478
"POST /admin/login/?next=/admin/ HTTP/1.1" 200 4478
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 4645
"GET /static/drf_spectacular_sidecar/swagger-ui-dist/swagger-ui.css HTTP/1.1" 200 155212
"GET /static/drf_spectacular_sidecar/swagger-ui-dist/swagger-ui-standalone-preset.js HTTP/1.1" 200 229223
"GET /static/drf_spectacular_sidecar/swagger-ui-dist/swagger-ui-bundle.js HTTP/1.1" 200 1485855
"GET /static/drf_spectacular_sidecar/swagger-ui-dist/favicon-32x32.png HTTP/1.1" 200 628
"GET /api/schema/ HTTP/1.1" 200 211105
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4302
"GET /static/admin/css/login.css HTTP/1.1" 200 951
"GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2808
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
"GET /static/admin/css/base.css HTTP/1.1" 200 22120
"GET /static/admin/css/responsive.css HTTP/1.1" 200 16565
"GET /static/admin/js/theme.js HTTP/1.1" 200 1653
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 4065
"OPTIONS /api/v1/users/login/ HTTP/1.1" 200 0
Not Found: /api/v1/users/login/
"POST /api/v1/users/login/ HTTP/1.1" 404 4090
Not Found: /api/v1/users/login/
"POST /api/v1/users/login/ HTTP/1.1" 404 4090
"GET / HTTP/1.1" 200 4645
"GET /api/schema/ HTTP/1.1" 200 211105
Unauthorized: /api/v1/auth/login/
"POST /api/v1/auth/login/ HTTP/1.1" 401 32
Not Found: /api/v1/users/login/
"POST /api/v1/users/login/ HTTP/1.1" 404 4090
Not Found: /api/v1/users/login/
"GET /api/v1/users/login/ HTTP/1.1" 404 4089
"OPTIONS /api/v1/login/ HTTP/1.1" 200 0
Not Found: /api/v1/login/
"POST /api/v1/login/ HTTP/1.1" 404 4072
"OPTIONS /api/v1/auth/login/ HTTP/1.1" 200 0
Unauthorized: /api/v1/auth/login/
"POST /api/v1/auth/login/ HTTP/1.1" 401 32
Unauthorized: /api/v1/auth/login/
"POST /api/v1/auth/login/ HTTP/1.1" 401 32
Bad Request: /api/v1/auth/pre-register-email/
"POST /api/v1/auth/pre-register-email/ HTTP/1.1" 400 40
"POST /api/v1/auth/pre-register-email/ HTTP/1.1" 200 51
C:\Users\maheer\Documents\projects\paper-final\backend_fixed\config\settings.py changed, reloading.
Watching for file changes with StatReloader
"POST /api/v1/auth/pre-register-email/ HTTP/1.1" 200 51
"POST /api/v1/auth/pre-register-verify/ HTTP/1.1" 200 51
Bad Request: /api/v1/auth/register/
"POST /api/v1/auth/register/ HTTP/1.1" 400 83
Bad Request: /api/v1/auth/register/
"POST /api/v1/auth/register/ HTTP/1.1" 400 83
Internal Server Error: /api/v1/auth/register/
Traceback (most recent call last):
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: users_user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\apps\users\views.py", line 126, in post
    user = serializer.save()
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\rest_framework\serializers.py", line 210, in save
    self.instance = self.create(validated_data)
                    ~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\apps\users\serializers.py", line 72, in create
    user = User.objects.create_user(
        username=username,
    ...<3 lines>...
        last_name=last_name[0] if last_name else ''
    )
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\contrib\auth\models.py", line 175, in create_user
    return self._create_user(username, email, password, **extra_fields)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\contrib\auth\models.py", line 163, in _create_user
    user.save(using=self._db)
    ~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\contrib\auth\base_user.py", line 65, in save
    super().save(*args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\models\base.py", line 902, in save
    self.save_base(
    ~~~~~~~~~~~~~~^
        using=using,
        ^^^^^^^^^^^^
    ...<2 lines>...
        update_fields=update_fields,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\models\base.py", line 1008, in save_base
    updated = self._save_table(
        raw,
    ...<4 lines>...
        update_fields,
    )
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\models\base.py", line 1169, in _save_table
    results = self._do_insert(
        cls._base_manager, using, fields, returning_fields, raw
    )
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\models\base.py", line 1210, in _do_insert
    return manager._insert(
           ~~~~~~~~~~~~~~~^
        [self],
        ^^^^^^^
    ...<3 lines>...
        raw=raw,
        ^^^^^^^^
    )
    ^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\models\query.py", line 1868, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1882, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: UNIQUE constraint failed: users_user.username
"POST /api/v1/auth/register/ HTTP/1.1" 500 26218
Internal Server Error: /api/v1/auth/register/
Traceback (most recent call last):
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: users_user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\apps\users\views.py", line 126, in post
    user = serializer.save()
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\rest_framework\serializers.py", line 210, in save
    self.instance = self.create(validated_data)
                    ~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\apps\users\serializers.py", line 72, in create
    user = User.objects.create_user(
        username=username,
    ...<3 lines>...
        last_name=last_name[0] if last_name else ''
    )
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\contrib\auth\models.py", line 175, in create_user
    return self._create_user(username, email, password, **extra_fields)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\contrib\auth\models.py", line 163, in _create_user
    user.save(using=self._db)
    ~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\contrib\auth\base_user.py", line 65, in save
    super().save(*args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\models\base.py", line 902, in save
    self.save_base(
    ~~~~~~~~~~~~~~^
        using=using,
        ^^^^^^^^^^^^
    ...<2 lines>...
        update_fields=update_fields,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\models\base.py", line 1008, in save_base
    updated = self._save_table(
        raw,
    ...<4 lines>...
        update_fields,
    )
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\models\base.py", line 1169, in _save_table
    results = self._do_insert(
        cls._base_manager, using, fields, returning_fields, raw
    )
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\models\base.py", line 1210, in _do_insert
    return manager._insert(
           ~~~~~~~~~~~~~~~^
        [self],
        ^^^^^^^
    ...<3 lines>...
        raw=raw,
        ^^^^^^^^
    )
    ^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\models\query.py", line 1868, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1882, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: UNIQUE constraint failed: users_user.username
"POST /api/v1/auth/register/ HTTP/1.1" 500 26218
Internal Server Error: /api/v1/auth/register/
Traceback (most recent call last):
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: users_user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\apps\users\views.py", line 126, in post
    user = serializer.save()
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\rest_framework\serializers.py", line 210, in save
    self.instance = self.create(validated_data)
                    ~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\apps\users\serializers.py", line 72, in create
    user = User.objects.create_user(
        username=username,
    ...<3 lines>...
        last_name=last_name[0] if last_name else ''
    )
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\contrib\auth\models.py", line 175, in create_user
    return self._create_user(username, email, password, **extra_fields)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\contrib\auth\models.py", line 163, in _create_user
    user.save(using=self._db)
    ~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\contrib\auth\base_user.py", line 65, in save
    super().save(*args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\models\base.py", line 902, in save
    self.save_base(
    ~~~~~~~~~~~~~~^
        using=using,
        ^^^^^^^^^^^^
    ...<2 lines>...
        update_fields=update_fields,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\models\base.py", line 1008, in save_base
    updated = self._save_table(
        raw,
    ...<4 lines>...
        update_fields,
    )
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\models\base.py", line 1169, in _save_table
    results = self._do_insert(
        cls._base_manager, using, fields, returning_fields, raw
    )
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\models\base.py", line 1210, in _do_insert
    return manager._insert(
           ~~~~~~~~~~~~~~~^
        [self],
        ^^^^^^^
    ...<3 lines>...
        raw=raw,
        ^^^^^^^^
    )
    ^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\models\query.py", line 1868, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1882, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: UNIQUE constraint failed: users_user.username
"POST /api/v1/auth/register/ HTTP/1.1" 500 26218
Watching for file changes with StatReloader
Bad Request: /api/v1/auth/register/
"POST /api/v1/auth/register/ HTTP/1.1" 400 56
"POST /api/v1/auth/pre-register-email/ HTTP/1.1" 200 51
"POST /api/v1/auth/pre-register-verify/ HTTP/1.1" 200 51
Internal Server Error: /api/v1/auth/register/
Traceback (most recent call last):
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: users_user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\apps\users\views.py", line 126, in post
    user = serializer.save()
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\rest_framework\serializers.py", line 210, in save
    self.instance = self.create(validated_data)
                    ~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\apps\users\serializers.py", line 72, in create
    user = User.objects.create_user(
        username=username,
    ...<3 lines>...
        last_name=last_name[0] if last_name else ''
    )
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\contrib\auth\models.py", line 175, in create_user
    return self._create_user(username, email, password, **extra_fields)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\contrib\auth\models.py", line 163, in _create_user
    user.save(using=self._db)
    ~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\contrib\auth\base_user.py", line 65, in save
    super().save(*args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\models\base.py", line 902, in save
    self.save_base(
    ~~~~~~~~~~~~~~^
        using=using,
        ^^^^^^^^^^^^
    ...<2 lines>...
        update_fields=update_fields,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\models\base.py", line 1008, in save_base
    updated = self._save_table(
        raw,
    ...<4 lines>...
        update_fields,
    )
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\models\base.py", line 1169, in _save_table
    results = self._do_insert(
        cls._base_manager, using, fields, returning_fields, raw
    )
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\models\base.py", line 1210, in _do_insert
    return manager._insert(
           ~~~~~~~~~~~~~~~^
        [self],
        ^^^^^^^
    ...<3 lines>...
        raw=raw,
        ^^^^^^^^
    )
    ^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\models\query.py", line 1868, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1882, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: UNIQUE constraint failed: users_user.username
"POST /api/v1/auth/register/ HTTP/1.1" 500 26218
C:\Users\maheer\Documents\projects\paper-final\backend_fixed\apps\users\serializers.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\maheer\Documents\projects\paper-final\backend_fixed\apps\users\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Bad Request: /api/v1/auth/register/
"POST /api/v1/auth/register/ HTTP/1.1" 400 56
"POST /api/v1/auth/pre-register-email/ HTTP/1.1" 200 51
"POST /api/v1/auth/pre-register-verify/ HTTP/1.1" 200 51
Internal Server Error: /api/v1/auth/register/
Traceback (most recent call last):
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\apps\users\views.py", line 126, in post
    user = serializer.save()
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\rest_framework\serializers.py", line 210, in save
    self.instance = self.create(validated_data)
                    ~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\apps\users\serializers.py", line 73, in create
    user = User.objects.create_user(
        email=email,
    ...<2 lines>...
        last_name=last_name[0] if last_name else ''
    )
TypeError: UserManager.create_user() missing 1 required positional argument: 'username'
"POST /api/v1/auth/register/ HTTP/1.1" 500 21844
C:\Users\maheer\Documents\projects\paper-final\backend_fixed\apps\users\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\maheer\Documents\projects\paper-final\backend_fixed\apps\users\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\maheer\Documents\projects\paper-final\backend_fixed\apps\users\views.py changed, reloading.
Watching for file changes with StatReloader
Bad Request: /api/v1/auth/register/
"POST /api/v1/auth/register/ HTTP/1.1" 400 56
"GET / HTTP/1.1" 200 4645
"GET /static/drf_spectacular_sidecar/swagger-ui-dist/swagger-ui.css HTTP/1.1" 304 0
"GET /static/drf_spectacular_sidecar/swagger-ui-dist/swagger-ui-standalone-preset.js HTTP/1.1" 304 0
"GET /static/drf_spectacular_sidecar/swagger-ui-dist/swagger-ui-bundle.js HTTP/1.1" 304 0
"GET /api/schema/ HTTP/1.1" 200 210291
"POST /api/v1/auth/pre-register-email/ HTTP/1.1" 200 51
Bad Request: /api/v1/auth/pre-register-verify/
"POST /api/v1/auth/pre-register-verify/ HTTP/1.1" 400 49
"POST /api/v1/auth/pre-register-verify/ HTTP/1.1" 200 51
Bad Request: /api/v1/auth/register/
"POST /api/v1/auth/register/ HTTP/1.1" 400 104
Internal Server Error: /api/v1/auth/register/
Traceback (most recent call last):
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\apps\users\views.py", line 128, in post
    user = serializer.save()
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\venv\Lib\site-packages\rest_framework\serializers.py", line 210, in save
    self.instance = self.create(validated_data)
                    ~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\maheer\Documents\projects\paper-final\backend_fixed\apps\users\serializers.py", line 73, in create
    user = User.objects.create_user(
        email=email,
    ...<2 lines>...
        last_name=last_name[0] if last_name else ''
    )
TypeError: UserManager.create_user() missing 1 required positional argument: 'username'
"POST /api/v1/auth/register/ HTTP/1.1" 500 21844
Not Found: /.well-known/appspecific/com.chrome.devtools.json
"GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 4176
"GET /static/drf_spectacular_sidecar/swagger-ui-dist/swagger-ui.css.map HTTP/1.1" 200 258968
C:\Users\maheer\Documents\projects\paper-final\backend_fixed\apps\users\models.py changed, reloading.
Watching for file changes with StatReloader
Bad Request: /api/v1/auth/register/
"POST /api/v1/auth/register/ HTTP/1.1" 400 56
"POST /api/v1/auth/pre-register-email/ HTTP/1.1" 200 51
"POST /api/v1/auth/pre-register-verify/ HTTP/1.1" 200 51
"POST /api/v1/auth/register/ HTTP/1.1" 201 38
"POST /api/v1/auth/login/ HTTP/1.1" 200 920
"OPTIONS /api/v1/auth/papers/generate/ai/ HTTP/1.1" 200 0
Not Found: /api/v1/auth/papers/generate/ai/
"POST /api/v1/auth/papers/generate/ai/ HTTP/1.1" 404 7615
"OPTIONS /api/v1/papers/generate/ai/ HTTP/1.1" 200 0
"POST /api/v1/papers/generate/ai/ HTTP/1.1" 200 7495
"POST /api/v1/papers/generate/ai/ HTTP/1.1" 200 7481
"POST /api/v1/papers/generate/ai/ HTTP/1.1" 200 7511
"POST /admin/login/?next=/admin/ HTTP/1.1" 200 4484
"GET /static/admin/css/base.css HTTP/1.1" 304 0
"GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
"GET /static/admin/css/login.css HTTP/1.1" 304 0
"GET /static/admin/css/responsive.css HTTP/1.1" 304 0
"GET /static/admin/js/theme.js HTTP/1.1" 304 0
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
"POST /admin/login/?next=/admin/ HTTP/1.1" 200 4478
Watching for file changes with StatReloader
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4302
"POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
"GET /admin/ HTTP/1.1" 200 20309
"GET /static/admin/css/dashboard.css HTTP/1.1" 200 441
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
"GET /admin/core/llmconfiguration/ HTTP/1.1" 200 19233
"GET /static/admin/css/changelists.css HTTP/1.1" 200 6878
"GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
"GET /static/admin/js/core.js HTTP/1.1" 200 6208
"GET /static/admin/js/actions.js HTTP/1.1" 200 8076
"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 9777
"GET /static/admin/js/urlify.js HTTP/1.1" 200 7887
"GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
"GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 285314
"GET /static/admin/js/filters.js HTTP/1.1" 200 978
"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 325171
"GET /admin/core/llmmodel/ HTTP/1.1" 200 23862
"GET /static/admin/img/search.svg HTTP/1.1" 200 458
"GET /static/admin/img/icon-no.svg HTTP/1.1" 200 560
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
"GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
"GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 581
"GET /admin/core/llmconfiguration/ HTTP/1.1" 200 19233
"GET /admin/core/llmconfiguration/1/change/ HTTP/1.1" 200 30028
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /static/admin/css/forms.css HTTP/1.1" 200 8525
"GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586
"GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 200 392
"GET /static/admin/css/widgets.css HTTP/1.1" 200 11991
"GET /static/admin/js/change_form.js HTTP/1.1" 200 606
"GET /admin/core/prompttemplate/ HTTP/1.1" 200 25376
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /admin/papers/generatedpaper/ HTTP/1.1" 200 34582
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /admin/token_blacklist/outstandingtoken/ HTTP/1.1" 200 20460
"GET /admin/papers/paperformat/ HTTP/1.1" 200 24060
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"POST /api/v1/papers/generate/ai/ HTTP/1.1" 200 7511
